### ISSUE TITLE
Investigate why y-axis on graphs is -100 instead of 0

### ISSUE THREAD

**Issue by bdeterling** [bdeterling/axiom#18]

**Comment by jasonperrone** [comment]
Have you seen this on regular line graphs, or only multiseries ones?

**Comment by bdeterling** [comment]
I think both.

**Comment by jasonperrone** [comment]
Can't reproduce so far on regular ones. I'll look into some sensible flot defaults we're not using.

**Comment by jasonperrone** [comment]
It's probably just because we're letting flot figure it out and it pads to give context. The other option is to take the min and max values, pad them by some percent and use that as min and max ticks, but then we're pretty much just replicating what it's already trying to do.

**Comment by jasonperrone** [comment]
yeah, there's a -1 in the data. You can see the dot if you look hard enough. So, it's taking the max value which is like 2,000 and factoring in that -1 and so it's coming up with that range. I can't hardcode it to be 0 or we won't be plotting negative values. Not sure it's worth doing anything with it.

**Comment by jasonperrone** [comment]
Based on my investigation, I don't think we need to do anything.

**Comment by bdeterling** [comment]
Maybe we should have data types of positive numbers versus all numbers so we could filter out bad data. I will save it for a rainy day.

**Comment by jasonperrone** [comment]
Yeah, that's a good one. Or maybe they should find out why their data is flat out like a lizard drinkin
